#!/usr/bin/env python3
"""Simple CLI shim for agentic-brain commands.
Usage: agentic-brain loadtest --users 100 --duration 60 --target http://.../
"""
import sys
import argparse
from agentic_brain.benchmark import load_test


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    parser = argparse.ArgumentParser(prog='agentic-brain')
    sub = parser.add_subparsers(dest='cmd')

    p = sub.add_parser('loadtest')
    p.add_argument('--users', type=int, default=100)
    p.add_argument('--duration', type=int, default=60)
    p.add_argument('--target', type=str, default='http://127.0.0.1:8000/')

    args = parser.parse_args(argv)
    if args.cmd == 'loadtest':
        print(f"Starting loadtest users={args.users} duration={args.duration} target={args.target}")
        out = load_test.run_sustained_load(args.target, users=args.users, duration_s=args.duration)
        print(out)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
