# SPDX-License-Identifier: Apache-2.0
"""Security roles, guards, agent wrappers, LLM controls, and OWASP auditing."""

from .base_agent import (
    BackgroundWorker,
    BaseSecureAgent,
    EventProcessor,
    ExploreAgent,
    TaskAgent,
)
from .guards import (
    SecurityGuard,
    SecurityViolation,
    check_command_allowed,
    check_file_access,
    get_or_create_guard,
    get_security_guard,
    require_admin,
    require_role,
    require_user_or_above,
    reset_security_guard,
    set_security_guard,
)
from .llm_guard import LLMRolePermissions, LLMSecurityGuard
from .owasp_checks import (
    CodeAnalyzer,
    OWASPAuditor,
    OWASPCategory,
    RegexPatternChecker,
    SecurityIssue,
    Severity,
    audit_and_report,
)
from .pentest import (
    COMMAND_INJECTION_VECTORS,
    CYPHER_INJECTION_VECTORS,
    PATH_TRAVERSAL_VECTORS,
    PROMPT_INJECTION_VECTORS,
    SQL_INJECTION_VECTORS,
    XSS_VECTORS,
    PentestFinding,
    PentestReport,
    PentestSuite,
    PentestVector,
    build_xss_header_report,
    run_security_pentest,
)
from .platform_security import (
    STANDALONE_PROFILE,
    WOOCOMMERCE_PROFILE,
    AccessLevel,
    PlatformSecurityProfile,
    normalize_endpoint,
)
from .prompt_filter import PromptFilter, PromptFilterError
from .roles import (
    DANGEROUS_COMMAND_PATTERNS,
    ROLE_PERMISSIONS,
    RolePermissions,
    SecurityRole,
    get_permissions,
    is_dangerous_command,
)
from .tool_guard import (
    EXPENSIVE_TOOLS,
    block_expensive_for_guest,
    can_use_tool,
    check_tool_access,
    check_web_search_allowed,
    get_allowed_tools,
    is_tool_expensive,
)
from .utils import (
    constant_time_compare,
    generate_secure_token,
    get_secret_from_vault,
    hash_password,
    is_development_mode,
    is_production_mode,
    validate_api_key,
    validate_jwt_secret,
    verify_password,
)

__all__ = [
    "BackgroundWorker",
    "BaseSecureAgent",
    "DANGEROUS_COMMAND_PATTERNS",
    "EventProcessor",
    "ExploreAgent",
    "LLMRolePermissions",
    "AccessLevel",
    "LLMSecurityGuard",
    "PlatformSecurityProfile",
    "PromptFilter",
    "PromptFilterError",
    "PentestFinding",
    "PentestReport",
    "PentestSuite",
    "PentestVector",
    "SQL_INJECTION_VECTORS",
    "CYPHER_INJECTION_VECTORS",
    "PROMPT_INJECTION_VECTORS",
    "PATH_TRAVERSAL_VECTORS",
    "COMMAND_INJECTION_VECTORS",
    "XSS_VECTORS",
    "build_xss_header_report",
    "run_security_pentest",
    "ROLE_PERMISSIONS",
    "RolePermissions",
    "SecurityGuard",
    "SecurityRole",
    "SecurityViolation",
    "TaskAgent",
    "check_command_allowed",
    "check_file_access",
    "check_tool_access",
    "check_web_search_allowed",
    "get_or_create_guard",
    "get_allowed_tools",
    "get_permissions",
    "get_security_guard",
    "is_dangerous_command",
    "is_tool_expensive",
    "STANDALONE_PROFILE",
    "WOOCOMMERCE_PROFILE",
    "normalize_endpoint",
    "EXPENSIVE_TOOLS",
    "block_expensive_for_guest",
    "can_use_tool",
    "require_admin",
    "require_role",
    "require_user_or_above",
    "reset_security_guard",
    "set_security_guard",
    # OWASP Auditing
    "CodeAnalyzer",
    "OWASPAuditor",
    "OWASPCategory",
    "RegexPatternChecker",
    "SecurityIssue",
    "Severity",
    "audit_and_report",
    # Security Utilities
    "constant_time_compare",
    "generate_secure_token",
    "get_secret_from_vault",
    "hash_password",
    "is_development_mode",
    "is_production_mode",
    "validate_api_key",
    "validate_jwt_secret",
    "verify_password",
]
