# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Joseph Webber

"""
Project Aria — Live Voice Daemon.

A background daemon that keeps the live voice session alive, surviving
terminal close.  Manages PID files for clean start/stop and optionally
integrates with macOS ``launchd`` for auto-start at login.

Architecture
============

::

    ab voice live start
        └─> LiveVoiceDaemon.start()
                ├── write PID file
                ├── create LiveVoiceSession
                ├── listen loop in daemon thread
                └── clean up PID on stop

The daemon does NOT fork into a separate process — it runs a background
*thread* inside the current process (for MCP / CLI use).  The PID file
tracks the *host process* so ``ab voice live --stop`` can signal it.

For true detached operation, use the launchd plist generated by
:func:`install_launchd_plist`.
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)

# ── Paths ────────────────────────────────────────────────────────────

_RUN_DIR = Path.home() / ".agentic-brain"
PID_FILE = _RUN_DIR / "live-voice.pid"
STATE_FILE = _RUN_DIR / "live-voice-state.json"
LAUNCHD_PLIST_PATH = (
    Path.home()
    / "Library"
    / "LaunchAgents"
    / "com.agentic-brain.live-voice.plist"
)
LAUNCHD_LABEL = "com.agentic-brain.live-voice"


# ── Daemon config ────────────────────────────────────────────────────

@dataclass
class DaemonConfig:
    """Configuration for the live voice daemon."""

    wake_words: tuple[str, ...] = ("hey karen", "hey brain")
    session_timeout: float = 30.0
    voice: str = "Karen"
    rate: int = 155
    use_whisper: bool = True
    whisper_model: str = "base.en"
    response_callback: Optional[Callable[[str], str]] = None


# ── Daemon class ─────────────────────────────────────────────────────

class LiveVoiceDaemon:
    """Background daemon wrapping a :class:`LiveVoiceSession`.

    Manages PID file lifecycle so the daemon can be controlled via CLI
    commands (``--status``, ``--stop``).
    """

    def __init__(self, config: Optional[DaemonConfig] = None) -> None:
        self._config = config or DaemonConfig()
        self._session: Any = None
        self._thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self._started_at: Optional[float] = None

    # ── Public API ───────────────────────────────────────────────

    def start(self) -> dict[str, Any]:
        """Start the daemon.  Returns a status dict."""
        if self.is_running:
            return {"ok": False, "error": "Daemon already running"}

        _RUN_DIR.mkdir(parents=True, exist_ok=True)

        from agentic_brain.voice.live_session import (
            LiveSessionConfig,
            LiveVoiceSession,
        )

        session_config = LiveSessionConfig(
            wake_words=self._config.wake_words,
            session_timeout_secs=self._config.session_timeout,
            voice=self._config.voice,
            rate=self._config.rate,
            require_wake_word=True,
            use_whisper=self._config.use_whisper,
            whisper_model=self._config.whisper_model,
            response_callback=self._config.response_callback,
        )
        self._session = LiveVoiceSession(config=session_config)
        ok = self._session.start()
        if not ok:
            return {
                "ok": False,
                "error": "Microphone unavailable — install PyAudio",
            }

        self._stop_event.clear()
        self._started_at = time.monotonic()
        self._write_pid()
        self._write_state("running")

        self._thread = threading.Thread(
            target=self._monitor_loop,
            name="live-voice-daemon",
            daemon=True,
        )
        self._thread.start()

        return {"ok": True, "pid": os.getpid(), **self._session.status()}

    def stop(self) -> dict[str, Any]:
        """Stop the daemon and clean up."""
        self._stop_event.set()

        result: dict[str, Any] = {"ok": True}
        if self._session:
            result.update(self._session.stop())

        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=5.0)

        self._remove_pid()
        self._write_state("stopped")
        return result

    def status(self) -> dict[str, Any]:
        """Return a snapshot of daemon state."""
        running = self.is_running
        info: dict[str, Any] = {
            "daemon_running": running,
            "pid": os.getpid() if running else None,
            "uptime_s": (
                round(time.monotonic() - self._started_at, 1)
                if self._started_at and running
                else 0
            ),
        }
        if self._session:
            info["session"] = self._session.status()
        return info

    @property
    def is_running(self) -> bool:
        return (
            self._session is not None
            and self._session.is_running
            and not self._stop_event.is_set()
        )

    # ── Monitor loop ─────────────────────────────────────────────

    def _monitor_loop(self) -> None:
        """Runs in daemon thread.  Watches session health."""
        while not self._stop_event.wait(timeout=2.0):
            if self._session and not self._session.is_running:
                logger.info("LiveVoiceDaemon: session ended naturally")
                break
        self._remove_pid()
        self._write_state("stopped")

    # ── PID file management ──────────────────────────────────────

    def _write_pid(self) -> None:
        try:
            PID_FILE.write_text(str(os.getpid()))
        except OSError as exc:
            logger.warning("Cannot write PID file: %s", exc)

    @staticmethod
    def _remove_pid() -> None:
        try:
            PID_FILE.unlink(missing_ok=True)
        except OSError:
            pass

    def _write_state(self, state: str) -> None:
        payload = {
            "state": state,
            "pid": os.getpid(),
            "timestamp": time.time(),
            "config": {
                "voice": self._config.voice,
                "rate": self._config.rate,
                "wake_words": list(self._config.wake_words),
                "session_timeout": self._config.session_timeout,
                "use_whisper": self._config.use_whisper,
            },
        }
        try:
            STATE_FILE.write_text(json.dumps(payload, indent=2))
        except OSError as exc:
            logger.warning("Cannot write state file: %s", exc)


# ── Module-level helpers ─────────────────────────────────────────────

_daemon: Optional[LiveVoiceDaemon] = None
_daemon_lock = threading.Lock()


def get_daemon() -> Optional[LiveVoiceDaemon]:
    """Return the module singleton (or None)."""
    return _daemon


def start_daemon(config: Optional[DaemonConfig] = None) -> dict[str, Any]:
    """Start the singleton daemon.  Returns status dict."""
    global _daemon
    with _daemon_lock:
        if _daemon and _daemon.is_running:
            return {"ok": False, "error": "Already running", **_daemon.status()}
        _daemon = LiveVoiceDaemon(config)
        return _daemon.start()


def stop_daemon() -> dict[str, Any]:
    """Stop the singleton daemon."""
    global _daemon
    with _daemon_lock:
        if not _daemon or not _daemon.is_running:
            return {"ok": True, "message": "Not running"}
        result = _daemon.stop()
        _daemon = None
        return result


def daemon_status() -> dict[str, Any]:
    """Return current daemon status (reads PID file if no in-process daemon)."""
    with _daemon_lock:
        if _daemon:
            return _daemon.status()

    # Check for out-of-process daemon via PID file
    return read_pid_status()


def read_pid_status() -> dict[str, Any]:
    """Read status from the PID file (for cross-process queries)."""
    if not PID_FILE.exists():
        return {"daemon_running": False, "message": "No PID file"}

    try:
        pid = int(PID_FILE.read_text().strip())
    except (ValueError, OSError):
        return {"daemon_running": False, "message": "Invalid PID file"}

    alive = _pid_alive(pid)

    state_info: dict[str, Any] = {}
    if STATE_FILE.exists():
        try:
            state_info = json.loads(STATE_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    return {
        "daemon_running": alive,
        "pid": pid,
        "state": state_info.get("state", "unknown"),
        "config": state_info.get("config", {}),
    }


def _pid_alive(pid: int) -> bool:
    """Check whether a PID is alive (POSIX only)."""
    try:
        os.kill(pid, 0)
        return True
    except (OSError, ProcessLookupError):
        return False


def signal_stop() -> bool:
    """Send SIGTERM to the daemon process identified by the PID file.

    Returns True if the signal was sent successfully.
    """
    if not PID_FILE.exists():
        return False
    try:
        pid = int(PID_FILE.read_text().strip())
    except (ValueError, OSError):
        return False

    if pid == os.getpid():
        # Same process — just call stop_daemon
        stop_daemon()
        return True

    try:
        os.kill(pid, signal.SIGTERM)
        return True
    except (OSError, ProcessLookupError):
        PID_FILE.unlink(missing_ok=True)
        return False


# ── launchd integration ──────────────────────────────────────────────

_PLIST_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{python}</string>
        <string>-m</string>
        <string>agentic_brain.cli</string>
        <string>voice</string>
        <string>live</string>
        <string>start</string>
        <string>--daemon</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{log_dir}/live-voice-stdout.log</string>
    <key>StandardErrorPath</key>
    <string>{log_dir}/live-voice-stderr.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
"""


def install_launchd_plist() -> dict[str, Any]:
    """Write a launchd plist for auto-start at login.

    Returns status dict with path and instructions.
    """
    if os.uname().sysname != "Darwin":
        return {"ok": False, "error": "launchd is macOS only"}

    log_dir = _RUN_DIR / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)

    plist_content = _PLIST_TEMPLATE.format(
        label=LAUNCHD_LABEL,
        python=sys.executable,
        log_dir=str(log_dir),
    )

    try:
        LAUNCHD_PLIST_PATH.parent.mkdir(parents=True, exist_ok=True)
        LAUNCHD_PLIST_PATH.write_text(plist_content)
    except OSError as exc:
        return {"ok": False, "error": f"Cannot write plist: {exc}"}

    return {
        "ok": True,
        "path": str(LAUNCHD_PLIST_PATH),
        "load_command": f"launchctl load {LAUNCHD_PLIST_PATH}",
        "unload_command": f"launchctl unload {LAUNCHD_PLIST_PATH}",
    }


def uninstall_launchd_plist() -> dict[str, Any]:
    """Unload and remove the launchd plist."""
    if os.uname().sysname != "Darwin":
        return {"ok": False, "error": "launchd is macOS only"}

    if LAUNCHD_PLIST_PATH.exists():
        try:
            subprocess.run(
                ["launchctl", "unload", str(LAUNCHD_PLIST_PATH)],
                capture_output=True,
                timeout=10,
            )
        except Exception:
            pass

        try:
            LAUNCHD_PLIST_PATH.unlink()
        except OSError as exc:
            return {"ok": False, "error": str(exc)}

    return {"ok": True, "message": "Plist removed"}


def _set_daemon_for_testing(d: Optional[LiveVoiceDaemon]) -> None:
    """Replace the global daemon — **test-only**."""
    global _daemon
    _daemon = d
