#!/usr/bin/env bash
set -euo pipefail

WP_PATH="/var/www/html"

wp_cli() {
  wp --path="$WP_PATH" --allow-root "$@"
}

log() {
  echo "[demo-entrypoint] $*"
}

# Start upstream WordPress entrypoint + Apache in the background.
# We do this first so wp-config.php / core files get created for fresh volumes.
/usr/local/bin/docker-entrypoint.sh apache2-foreground &
WP_PID=$!

term_handler() {
  log "Received termination signal; stopping WordPress (PID $WP_PID)"
  kill -TERM "$WP_PID" 2>/dev/null || true
  wait "$WP_PID" 2>/dev/null || true
}
trap term_handler TERM INT

# Wait for wp-config.php to appear (generated by upstream entrypoint)
log "Waiting for wp-config.php to be generated..."
for i in $(seq 1 60); do
  if [ -f "$WP_PATH/wp-config.php" ]; then
    break
  fi
  sleep 1
  if ! kill -0 "$WP_PID" 2>/dev/null; then
    log "WordPress process exited early"
    wait "$WP_PID" || true
    exit 1
  fi
done

# Wait for DB connectivity
log "Waiting for database connectivity..."
DB_OK=0
for i in $(seq 1 60); do
  if wp_cli db check >/dev/null 2>&1; then
    DB_OK=1
    break
  fi
  sleep 2
  if ! kill -0 "$WP_PID" 2>/dev/null; then
    log "WordPress process exited early"
    wait "$WP_PID" || true
    exit 1
  fi
done

if [ "$DB_OK" != "1" ]; then
  log "Database did not become ready in time"
  exit 1
fi

DEMO_SITE_URL="${DEMO_SITE_URL:-${WORDPRESS_INSTALL_URL:-http://localhost:8080}}"
DEMO_SITE_TITLE="${DEMO_SITE_TITLE:-Agentic Brain Demo Store}"
DEMO_ADMIN_USER="${DEMO_ADMIN_USER:-admin}"
DEMO_ADMIN_PASSWORD="${DEMO_ADMIN_PASSWORD:-Admin123!Demo}"
DEMO_ADMIN_EMAIL="${DEMO_ADMIN_EMAIL:-admin@agenticbrain.demo}"

# Install WordPress if needed
if ! wp_cli core is-installed >/dev/null 2>&1; then
  log "Installing WordPress core..."
  wp_cli core install \
    --url="$DEMO_SITE_URL" \
    --title="$DEMO_SITE_TITLE" \
    --admin_user="$DEMO_ADMIN_USER" \
    --admin_password="$DEMO_ADMIN_PASSWORD" \
    --admin_email="$DEMO_ADMIN_EMAIL" \
    --skip-email
else
  log "WordPress already installed"
fi

AUTO_PLUGINS="${WP_AGENTIC_BRAIN_AUTO_PLUGINS:-woocommerce agentic-brain}"

for plugin_slug in $AUTO_PLUGINS; do
  if [ "$plugin_slug" = "woocommerce" ]; then
    if ! wp_cli plugin is-installed woocommerce >/dev/null 2>&1; then
      log "Installing WooCommerce..."
      wp_cli plugin install woocommerce --activate
    else
      log "Ensuring WooCommerce is active..."
      wp_cli plugin activate woocommerce >/dev/null 2>&1 || true
    fi
    continue
  fi

  log "Ensuring $plugin_slug plugin is active..."
  wp_cli plugin activate "$plugin_slug" >/dev/null 2>&1 || true
done

# Create demo content (fallback if no sample-data import is provided)
log "Creating demo content (idempotent)..."
wp_cli eval '
$existing = get_posts(["post_type" => "product", "posts_per_page" => 1]);
if (!$existing) {
  if (!class_exists("WC_Product_Simple")) {
    echo "WooCommerce not loaded\n";
    return;
  }
  $products = [
    ["Demo Headphones", "Premium wireless headphones with noise cancellation", "199.99"],
    ["Demo Coffee Beans", "Single-origin organic coffee beans", "24.99"],
    ["Demo Water Bottle", "Insulated 750ml stainless steel bottle", "34.99"],
  ];
  foreach ($products as $p) {
    $product = new WC_Product_Simple();
    $product->set_name($p[0]);
    $product->set_description($p[1]);
    $product->set_regular_price($p[2]);
    $product->set_status("publish");
    $product->set_catalog_visibility("visible");
    $product->set_manage_stock(false);
    $product->save();
  }
  echo "Created demo products\n";
} else {
  echo "Demo products already exist\n";
}
' >/dev/null 2>&1 || true

# Import optional sample data if mounted into /demo/sample-data
if [ -d "/demo/sample-data" ]; then
  sample_xml=$(find /demo/sample-data -maxdepth 1 -type f -name '*.xml' | head -n 1 || true)
  if [ -n "$sample_xml" ]; then
    log "Importing sample data from $sample_xml..."
    wp_cli plugin install wordpress-importer --activate >/dev/null 2>&1 || true
    wp_cli import "$sample_xml" --authors=create >/dev/null 2>&1 || true
  fi
fi

log "Initialization complete; handing over to WordPress"
wait "$WP_PID"
